[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  # Disable email obfuscation
  email_obfuscation = false

[build.processing.images]
  compress = true
